/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAvatar: typeof import('./components/BaseAvatar/BaseAvatar.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon/BaseIcon.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    LoginBox: typeof import('./components/LoginBox/LoginBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
