/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAvatar: typeof import('./components/BaseAvatar/BaseAvatar.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon/BaseIcon.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
